server:
  port: 3032

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/payment_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:8888



#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#  pattern:
#    level: '%5p [${spring.application.name:}]'
#management:
#  tracing:
#    sampling:
#      probability: '1.0'





